fnPublishMQTTCron:
    name: fnPublishMQTTCron-${self:provider.stage}
    handler: src/IoT-Clients/fnPublishMQTTCron.fnPublishMQTTCron
    events:
      - schedule: cron(0/1 * * * ? *)
    memorySize: 256
    timeout: 60
    logRetentionInDays: 7
    iamRoleStatementsName: fnPublishMQTTCron-${self:provider.stage}
    iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "iot:*"
      Resource: '*'

# Not created yet
# fnAlarmCron: 
#     name: fnAlarmCron-${self:provider.stage}
#     handler: src/CloudWatch/fnAlarmCron.fnAlarmCron
#     events:
#       # - schedule: cron(0/1 * * * ? *)
#     memorySize: 2000
#     timeout: 900
#     logRetentionInDays: 7
#     iamRoleStatementsName: fnAlarmCron-${self:provider.stage}
#     iamRoleStatements:
#     - Effect: "Allow"
#       Action:
#       - "iot:*"
#       Resource: '*' 
#     - Effect: "Allow"
#       Action:
#       - "logs:*"
#       Resource: '*'  